/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Hero2nd: typeof import('./components/Hero2nd.vue')['default']
    Location: typeof import('./components/Location.vue')['default']
    MealPlan: typeof import('./components/MealPlan.vue')['default']
    MemberSuccess: typeof import('./components/MemberSuccess.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    QuickTip: typeof import('./components/QuickTip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonialCarousel: typeof import('./components/TestimonialCarousel.vue')['default']
    TrainingPackages: typeof import('./components/TrainingPackages.vue')['default']
    Transforms: typeof import('./components/Transforms.vue')['default']
  }
}
