/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AboutLayout: typeof import('./components/layout/AboutLayout.vue')['default']
    AccordionLayout: typeof import('./components/layout/AccordionLayout.vue')['default']
    BannerLayout: typeof import('./components/layout/BannerLayout.vue')['default']
    BentoGrid: typeof import('./components/BentoGrid.vue')['default']
    CardsRowLayout: typeof import('./components/layout/CardsRowLayout.vue')['default']
    CatalogLayout: typeof import('./components/layout/CatalogLayout.vue')['default']
    CatalogNutrition: typeof import('./components/CatalogNutrition.vue')['default']
    ClientsCarousel: typeof import('./components/ClientsCarousel.vue')['default']
    CTA: typeof import('./components/CTA.vue')['default']
    CTALayout: typeof import('./components/layout/CTALayout.vue')['default']
    Facts: typeof import('./components/Facts.vue')['default']
    Faqs: typeof import('./components/Faqs.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterLayout: typeof import('./components/layout/FooterLayout.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Hero2nd: typeof import('./components/Hero2nd.vue')['default']
    Hero3: typeof import('./components/Hero3.vue')['default']
    HeroLayout: typeof import('./components/layout/HeroLayout.vue')['default']
    HeroSplitLayout: typeof import('./components/layout/HeroSplitLayout.vue')['default']
    Important: typeof import('./components/Important.vue')['default']
    Location: typeof import('./components/Location.vue')['default']
    MealPlan: typeof import('./components/MealPlan.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PricingLayout: typeof import('./components/layout/PricingLayout.vue')['default']
    ReadyToTransform: typeof import('./components/ReadyToTransform.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./components/Services.vue')['default']
    StatsGridLayout: typeof import('./components/layout/StatsGridLayout.vue')['default']
    TrainingPackages: typeof import('./components/TrainingPackages.vue')['default']
    Transforms: typeof import('./components/Transforms.vue')['default']
  }
}
